// ─── Comprehensive Offline Food Nutrition Database ────────────────────
// All values are per 100g. Sources: USDA FoodData Central, IFCT (Indian Food Composition Tables)
// This database eliminates the need for any external API calls for nutrition data.

export interface FoodEntry {
  name: string;
  aliases: string[];        // Alternative names for matching
  category: FoodCategory;
  calories: number;         // kcal per 100g
  protein: number;          // grams per 100g
  carbs: number;            // grams per 100g
  fat: number;              // grams per 100g
  fiber: number;            // grams per 100g
  typical_serving_g: number; // Typical single serving in grams
  color_hints: string[];    // Dominant colors for image analysis hints
}

export type FoodCategory =
  | 'fruit'
  | 'vegetable'
  | 'grain'
  | 'bread'
  | 'rice'
  | 'pasta'
  | 'meat'
  | 'poultry'
  | 'seafood'
  | 'dairy'
  | 'egg'
  | 'legume'
  | 'nut'
  | 'snack'
  | 'sweet'
  | 'beverage'
  | 'curry'
  | 'soup'
  | 'salad'
  | 'sandwich'
  | 'pizza'
  | 'fast_food'
  | 'indian'
  | 'chinese'
  | 'japanese'
  | 'mexican'
  | 'dessert'
  | 'sauce'
  | 'oil'
  | 'other';

// ─── THE DATABASE ─────────────────────────────────────────────────────

export const FOOD_DATABASE: FoodEntry[] = [
  // ━━━ FRUITS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Apple',
    aliases: ['apple', 'red apple', 'green apple', 'seb'],
    category: 'fruit',
    calories: 52,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    fiber: 2.4,
    typical_serving_g: 180,
    color_hints: ['red', 'green', 'yellow'],
  },
  {
    name: 'Banana',
    aliases: ['banana', 'kela', 'plantain'],
    category: 'fruit',
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    typical_serving_g: 120,
    color_hints: ['yellow', 'white'],
  },
  {
    name: 'Orange',
    aliases: ['orange', 'santra', 'narangi', 'citrus'],
    category: 'fruit',
    calories: 47,
    protein: 0.9,
    carbs: 11.8,
    fat: 0.1,
    fiber: 2.4,
    typical_serving_g: 130,
    color_hints: ['orange'],
  },
  {
    name: 'Mango',
    aliases: ['mango', 'aam', 'alphonso', 'hapus'],
    category: 'fruit',
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    fiber: 1.6,
    typical_serving_g: 200,
    color_hints: ['yellow', 'orange', 'green'],
  },
  {
    name: 'Grapes',
    aliases: ['grapes', 'angoor', 'green grapes', 'red grapes', 'black grapes'],
    category: 'fruit',
    calories: 69,
    protein: 0.7,
    carbs: 18.1,
    fat: 0.2,
    fiber: 0.9,
    typical_serving_g: 150,
    color_hints: ['green', 'purple', 'red'],
  },
  {
    name: 'Watermelon',
    aliases: ['watermelon', 'tarbooj', 'tarbuj'],
    category: 'fruit',
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    fiber: 0.4,
    typical_serving_g: 280,
    color_hints: ['red', 'green'],
  },
  {
    name: 'Papaya',
    aliases: ['papaya', 'papita'],
    category: 'fruit',
    calories: 43,
    protein: 0.5,
    carbs: 10.8,
    fat: 0.3,
    fiber: 1.7,
    typical_serving_g: 150,
    color_hints: ['orange', 'yellow'],
  },
  {
    name: 'Guava',
    aliases: ['guava', 'amrood', 'amrud'],
    category: 'fruit',
    calories: 68,
    protein: 2.6,
    carbs: 14.3,
    fat: 1.0,
    fiber: 5.4,
    typical_serving_g: 100,
    color_hints: ['green', 'pink', 'white'],
  },
  {
    name: 'Pomegranate',
    aliases: ['pomegranate', 'anaar', 'anar'],
    category: 'fruit',
    calories: 83,
    protein: 1.7,
    carbs: 18.7,
    fat: 1.2,
    fiber: 4.0,
    typical_serving_g: 150,
    color_hints: ['red', 'pink'],
  },
  {
    name: 'Pineapple',
    aliases: ['pineapple', 'ananas'],
    category: 'fruit',
    calories: 50,
    protein: 0.5,
    carbs: 13.1,
    fat: 0.1,
    fiber: 1.4,
    typical_serving_g: 165,
    color_hints: ['yellow'],
  },
  {
    name: 'Strawberry',
    aliases: ['strawberry', 'strawberries'],
    category: 'fruit',
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2.0,
    typical_serving_g: 150,
    color_hints: ['red'],
  },
  {
    name: 'Blueberry',
    aliases: ['blueberry', 'blueberries'],
    category: 'fruit',
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    fiber: 2.4,
    typical_serving_g: 150,
    color_hints: ['blue', 'purple'],
  },
  {
    name: 'Coconut (fresh)',
    aliases: ['coconut', 'nariyal', 'fresh coconut'],
    category: 'fruit',
    calories: 354,
    protein: 3.3,
    carbs: 15.2,
    fat: 33.5,
    fiber: 9.0,
    typical_serving_g: 80,
    color_hints: ['white', 'brown'],
  },
  {
    name: 'Litchi',
    aliases: ['lychee', 'litchi', 'lichee'],
    category: 'fruit',
    calories: 66,
    protein: 0.8,
    carbs: 16.5,
    fat: 0.4,
    fiber: 1.3,
    typical_serving_g: 100,
    color_hints: ['red', 'white'],
  },
  {
    name: 'Chikoo (Sapota)',
    aliases: ['chikoo', 'sapota', 'sapodilla', 'chiku'],
    category: 'fruit',
    calories: 83,
    protein: 0.4,
    carbs: 20,
    fat: 1.1,
    fiber: 5.3,
    typical_serving_g: 100,
    color_hints: ['brown'],
  },
  {
    name: 'Kiwi',
    aliases: ['kiwi', 'kiwifruit'],
    category: 'fruit',
    calories: 61,
    protein: 1.1,
    carbs: 14.7,
    fat: 0.5,
    fiber: 3.0,
    typical_serving_g: 75,
    color_hints: ['green', 'brown'],
  },
  {
    name: 'Avocado',
    aliases: ['avocado', 'butter fruit'],
    category: 'fruit',
    calories: 160,
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    typical_serving_g: 150,
    color_hints: ['green', 'yellow'],
  },
  {
    name: 'Peach',
    aliases: ['peach', 'aadu'],
    category: 'fruit',
    calories: 39,
    protein: 0.9,
    carbs: 9.5,
    fat: 0.3,
    fiber: 1.5,
    typical_serving_g: 150,
    color_hints: ['orange', 'yellow', 'red'],
  },
  {
    name: 'Pear',
    aliases: ['pear', 'nashpati'],
    category: 'fruit',
    calories: 57,
    protein: 0.4,
    carbs: 15.2,
    fat: 0.1,
    fiber: 3.1,
    typical_serving_g: 180,
    color_hints: ['green', 'yellow'],
  },
  {
    name: 'Plum',
    aliases: ['plum', 'aloo bukhara'],
    category: 'fruit',
    calories: 46,
    protein: 0.7,
    carbs: 11.4,
    fat: 0.3,
    fiber: 1.4,
    typical_serving_g: 100,
    color_hints: ['purple', 'red'],
  },
  {
    name: 'Dates',
    aliases: ['dates', 'khajoor', 'khajur', 'medjool dates'],
    category: 'fruit',
    calories: 277,
    protein: 1.8,
    carbs: 75,
    fat: 0.2,
    fiber: 7.0,
    typical_serving_g: 40,
    color_hints: ['brown', 'dark brown'],
  },
  {
    name: 'Jackfruit',
    aliases: ['jackfruit', 'kathal', 'kathal'],
    category: 'fruit',
    calories: 95,
    protein: 1.7,
    carbs: 23.2,
    fat: 0.6,
    fiber: 1.5,
    typical_serving_g: 150,
    color_hints: ['yellow', 'green'],
  },

  // ━━━ VEGETABLES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Tomato',
    aliases: ['tomato', 'tamatar'],
    category: 'vegetable',
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    typical_serving_g: 120,
    color_hints: ['red'],
  },
  {
    name: 'Potato',
    aliases: ['potato', 'aloo', 'alu', 'boiled potato', 'baked potato'],
    category: 'vegetable',
    calories: 77,
    protein: 2.0,
    carbs: 17.5,
    fat: 0.1,
    fiber: 2.2,
    typical_serving_g: 150,
    color_hints: ['brown', 'yellow', 'white'],
  },
  {
    name: 'Onion',
    aliases: ['onion', 'pyaz', 'pyaaz', 'kanda'],
    category: 'vegetable',
    calories: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
    fiber: 1.7,
    typical_serving_g: 100,
    color_hints: ['white', 'red', 'purple'],
  },
  {
    name: 'Carrot',
    aliases: ['carrot', 'gajar'],
    category: 'vegetable',
    calories: 41,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    typical_serving_g: 80,
    color_hints: ['orange'],
  },
  {
    name: 'Spinach (cooked)',
    aliases: ['spinach', 'palak', 'cooked spinach'],
    category: 'vegetable',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    typical_serving_g: 100,
    color_hints: ['green'],
  },
  {
    name: 'Broccoli',
    aliases: ['broccoli', 'hari phool gobhi'],
    category: 'vegetable',
    calories: 34,
    protein: 2.8,
    carbs: 7.0,
    fat: 0.4,
    fiber: 2.6,
    typical_serving_g: 90,
    color_hints: ['green'],
  },
  {
    name: 'Cauliflower',
    aliases: ['cauliflower', 'phool gobhi', 'gobi'],
    category: 'vegetable',
    calories: 25,
    protein: 1.9,
    carbs: 5.0,
    fat: 0.3,
    fiber: 2.0,
    typical_serving_g: 100,
    color_hints: ['white'],
  },
  {
    name: 'Green Beans',
    aliases: ['green beans', 'french beans', 'string beans', 'sem'],
    category: 'vegetable',
    calories: 31,
    protein: 1.8,
    carbs: 7.0,
    fat: 0.1,
    fiber: 3.4,
    typical_serving_g: 100,
    color_hints: ['green'],
  },
  {
    name: 'Capsicum (Bell Pepper)',
    aliases: ['capsicum', 'bell pepper', 'shimla mirch', 'green pepper', 'red pepper'],
    category: 'vegetable',
    calories: 20,
    protein: 0.9,
    carbs: 4.6,
    fat: 0.2,
    fiber: 1.7,
    typical_serving_g: 120,
    color_hints: ['green', 'red', 'yellow'],
  },
  {
    name: 'Cucumber',
    aliases: ['cucumber', 'kheera', 'kakdi'],
    category: 'vegetable',
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    typical_serving_g: 150,
    color_hints: ['green'],
  },
  {
    name: 'Bitter Gourd',
    aliases: ['bitter gourd', 'karela', 'bitter melon'],
    category: 'vegetable',
    calories: 17,
    protein: 1.0,
    carbs: 3.7,
    fat: 0.2,
    fiber: 2.8,
    typical_serving_g: 100,
    color_hints: ['green'],
  },
  {
    name: 'Okra (Lady Finger)',
    aliases: ['okra', 'lady finger', 'bhindi'],
    category: 'vegetable',
    calories: 33,
    protein: 1.9,
    carbs: 7.5,
    fat: 0.2,
    fiber: 3.2,
    typical_serving_g: 100,
    color_hints: ['green'],
  },
  {
    name: 'Eggplant (Brinjal)',
    aliases: ['eggplant', 'brinjal', 'baingan', 'aubergine'],
    category: 'vegetable',
    calories: 25,
    protein: 1.0,
    carbs: 5.9,
    fat: 0.2,
    fiber: 3.0,
    typical_serving_g: 100,
    color_hints: ['purple'],
  },
  {
    name: 'Sweet Potato',
    aliases: ['sweet potato', 'shakarkand', 'shakarkandi'],
    category: 'vegetable',
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    fiber: 3.0,
    typical_serving_g: 130,
    color_hints: ['orange', 'brown'],
  },
  {
    name: 'Corn',
    aliases: ['corn', 'makai', 'bhutta', 'sweet corn', 'corn on the cob'],
    category: 'vegetable',
    calories: 86,
    protein: 3.3,
    carbs: 19.0,
    fat: 1.2,
    fiber: 2.7,
    typical_serving_g: 150,
    color_hints: ['yellow'],
  },
  {
    name: 'Mushroom',
    aliases: ['mushroom', 'mushrooms', 'khumbi', 'button mushroom'],
    category: 'vegetable',
    calories: 22,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
    fiber: 1.0,
    typical_serving_g: 80,
    color_hints: ['white', 'brown'],
  },
  {
    name: 'Cabbage',
    aliases: ['cabbage', 'patta gobhi', 'band gobhi'],
    category: 'vegetable',
    calories: 25,
    protein: 1.3,
    carbs: 5.8,
    fat: 0.1,
    fiber: 2.5,
    typical_serving_g: 100,
    color_hints: ['green', 'white'],
  },
  {
    name: 'Beetroot',
    aliases: ['beetroot', 'chukandar', 'beet'],
    category: 'vegetable',
    calories: 43,
    protein: 1.6,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    typical_serving_g: 100,
    color_hints: ['red', 'dark red'],
  },
  {
    name: 'Radish',
    aliases: ['radish', 'mooli', 'muli'],
    category: 'vegetable',
    calories: 16,
    protein: 0.7,
    carbs: 3.4,
    fat: 0.1,
    fiber: 1.6,
    typical_serving_g: 80,
    color_hints: ['white', 'red'],
  },

  // ━━━ RICE & GRAINS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'White Rice (cooked)',
    aliases: ['white rice', 'steamed rice', 'chawal', 'cooked rice', 'plain rice', 'basmati rice'],
    category: 'rice',
    calories: 130,
    protein: 2.7,
    carbs: 28.2,
    fat: 0.3,
    fiber: 0.4,
    typical_serving_g: 200,
    color_hints: ['white'],
  },
  {
    name: 'Brown Rice (cooked)',
    aliases: ['brown rice'],
    category: 'rice',
    calories: 111,
    protein: 2.6,
    carbs: 23.0,
    fat: 0.9,
    fiber: 1.8,
    typical_serving_g: 200,
    color_hints: ['brown'],
  },
  {
    name: 'Biryani',
    aliases: ['biryani', 'biriyani', 'chicken biryani', 'mutton biryani', 'veg biryani', 'hyderabadi biryani', 'dum biryani'],
    category: 'indian',
    calories: 175,
    protein: 7.5,
    carbs: 22.0,
    fat: 6.5,
    fiber: 0.6,
    typical_serving_g: 300,
    color_hints: ['yellow', 'orange', 'brown'],
  },
  {
    name: 'Pulao (Pilaf)',
    aliases: ['pulao', 'pilaf', 'pulav', 'veg pulao', 'jeera rice'],
    category: 'indian',
    calories: 140,
    protein: 3.0,
    carbs: 22.0,
    fat: 4.5,
    fiber: 0.5,
    typical_serving_g: 250,
    color_hints: ['yellow', 'white'],
  },
  {
    name: 'Oats (cooked)',
    aliases: ['oats', 'oatmeal', 'porridge', 'daliya'],
    category: 'grain',
    calories: 71,
    protein: 2.5,
    carbs: 12.0,
    fat: 1.5,
    fiber: 1.7,
    typical_serving_g: 240,
    color_hints: ['beige', 'white'],
  },
  {
    name: 'Quinoa (cooked)',
    aliases: ['quinoa'],
    category: 'grain',
    calories: 120,
    protein: 4.4,
    carbs: 21.3,
    fat: 1.9,
    fiber: 2.8,
    typical_serving_g: 185,
    color_hints: ['white', 'yellow'],
  },
  {
    name: 'Upma',
    aliases: ['upma', 'uppuma', 'rava upma'],
    category: 'indian',
    calories: 130,
    protein: 3.5,
    carbs: 18.0,
    fat: 5.0,
    fiber: 1.0,
    typical_serving_g: 200,
    color_hints: ['yellow', 'white'],
  },
  {
    name: 'Poha (Flattened Rice)',
    aliases: ['poha', 'flattened rice', 'chivda', 'beaten rice'],
    category: 'indian',
    calories: 160,
    protein: 3.0,
    carbs: 28.0,
    fat: 4.5,
    fiber: 1.0,
    typical_serving_g: 200,
    color_hints: ['yellow', 'white'],
  },
  {
    name: 'Idli',
    aliases: ['idli', 'idly', 'rice cake'],
    category: 'indian',
    calories: 58,
    protein: 2.0,
    carbs: 12.0,
    fat: 0.2,
    fiber: 0.5,
    typical_serving_g: 60,
    color_hints: ['white'],
  },
  {
    name: 'Dosa',
    aliases: ['dosa', 'masala dosa', 'plain dosa', 'paper dosa', 'rava dosa'],
    category: 'indian',
    calories: 168,
    protein: 3.9,
    carbs: 26.0,
    fat: 5.2,
    fiber: 0.7,
    typical_serving_g: 120,
    color_hints: ['golden', 'brown'],
  },

  // ━━━ BREAD & ROTI ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Roti (Chapati)',
    aliases: ['roti', 'chapati', 'chapatti', 'phulka', 'wheat roti'],
    category: 'bread',
    calories: 104,
    protein: 3.0,
    carbs: 18.3,
    fat: 2.6,
    fiber: 1.9,
    typical_serving_g: 40,
    color_hints: ['brown', 'golden'],
  },
  {
    name: 'Naan',
    aliases: ['naan', 'nan', 'butter naan', 'garlic naan', 'tandoori naan'],
    category: 'bread',
    calories: 262,
    protein: 8.7,
    carbs: 45.4,
    fat: 5.1,
    fiber: 2.0,
    typical_serving_g: 90,
    color_hints: ['golden', 'brown'],
  },
  {
    name: 'Paratha',
    aliases: ['paratha', 'parantha', 'aloo paratha', 'gobhi paratha', 'stuffed paratha', 'laccha paratha'],
    category: 'bread',
    calories: 260,
    protein: 5.0,
    carbs: 30.0,
    fat: 13.0,
    fiber: 1.5,
    typical_serving_g: 80,
    color_hints: ['golden', 'brown'],
  },
  {
    name: 'Puri',
    aliases: ['puri', 'poori', 'puchi'],
    category: 'bread',
    calories: 350,
    protein: 5.5,
    carbs: 40.0,
    fat: 18.5,
    fiber: 1.2,
    typical_serving_g: 30,
    color_hints: ['golden', 'brown'],
  },
  {
    name: 'White Bread',
    aliases: ['white bread', 'bread', 'toast', 'bread slice', 'sandwich bread'],
    category: 'bread',
    calories: 265,
    protein: 9.0,
    carbs: 49.0,
    fat: 3.2,
    fiber: 2.7,
    typical_serving_g: 30,
    color_hints: ['white', 'brown'],
  },
  {
    name: 'Whole Wheat Bread',
    aliases: ['whole wheat bread', 'brown bread', 'atta bread', 'multigrain bread'],
    category: 'bread',
    calories: 247,
    protein: 13.0,
    carbs: 41.3,
    fat: 3.4,
    fiber: 6.8,
    typical_serving_g: 30,
    color_hints: ['brown'],
  },
  {
    name: 'Bhatura',
    aliases: ['bhatura', 'bhatoora', 'chole bhature'],
    category: 'bread',
    calories: 330,
    protein: 7.0,
    carbs: 40.0,
    fat: 16.0,
    fiber: 1.0,
    typical_serving_g: 100,
    color_hints: ['golden', 'brown'],
  },
  {
    name: 'Kulcha',
    aliases: ['kulcha', 'amritsari kulcha', 'paneer kulcha'],
    category: 'bread',
    calories: 280,
    protein: 7.5,
    carbs: 42.0,
    fat: 9.0,
    fiber: 1.5,
    typical_serving_g: 80,
    color_hints: ['golden', 'brown'],
  },

  // ━━━ PASTA & NOODLES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Pasta (cooked)',
    aliases: ['pasta', 'spaghetti', 'penne', 'macaroni', 'fusilli', 'fettuccine'],
    category: 'pasta',
    calories: 131,
    protein: 5.0,
    carbs: 25.4,
    fat: 1.1,
    fiber: 1.8,
    typical_serving_g: 200,
    color_hints: ['yellow', 'white'],
  },
  {
    name: 'Maggi Noodles',
    aliases: ['maggi', 'instant noodles', 'maggi noodles', 'ramen', 'cup noodles'],
    category: 'pasta',
    calories: 205,
    protein: 4.5,
    carbs: 27.0,
    fat: 8.8,
    fiber: 1.2,
    typical_serving_g: 200,
    color_hints: ['yellow'],
  },
  {
    name: 'Hakka Noodles',
    aliases: ['hakka noodles', 'chow mein', 'veg noodles', 'chowmein', 'stir fried noodles'],
    category: 'chinese',
    calories: 150,
    protein: 4.0,
    carbs: 24.0,
    fat: 5.0,
    fiber: 1.5,
    typical_serving_g: 250,
    color_hints: ['yellow', 'brown'],
  },

  // ━━━ DAL & LEGUMES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Dal (Lentil Soup)',
    aliases: ['dal', 'daal', 'toor dal', 'moong dal', 'masoor dal', 'arhar dal', 'chana dal', 'yellow dal'],
    category: 'legume',
    calories: 104,
    protein: 7.0,
    carbs: 13.0,
    fat: 2.5,
    fiber: 3.0,
    typical_serving_g: 200,
    color_hints: ['yellow', 'orange'],
  },
  {
    name: 'Rajma (Kidney Beans)',
    aliases: ['rajma', 'kidney beans', 'rajma chawal', 'red beans'],
    category: 'legume',
    calories: 127,
    protein: 8.7,
    carbs: 22.8,
    fat: 0.5,
    fiber: 6.4,
    typical_serving_g: 200,
    color_hints: ['red', 'brown'],
  },
  {
    name: 'Chole (Chickpeas)',
    aliases: ['chole', 'chickpeas', 'chana masala', 'chana', 'garbanzo beans', 'kabuli chana'],
    category: 'legume',
    calories: 164,
    protein: 8.9,
    carbs: 27.4,
    fat: 2.6,
    fiber: 7.6,
    typical_serving_g: 200,
    color_hints: ['brown', 'yellow'],
  },
  {
    name: 'Sambar',
    aliases: ['sambar', 'sambhar'],
    category: 'indian',
    calories: 65,
    protein: 3.5,
    carbs: 8.0,
    fat: 2.5,
    fiber: 2.0,
    typical_serving_g: 200,
    color_hints: ['orange', 'yellow'],
  },
  {
    name: 'Rasam',
    aliases: ['rasam', 'chaaru', 'saaru'],
    category: 'indian',
    calories: 25,
    protein: 1.0,
    carbs: 4.0,
    fat: 0.5,
    fiber: 0.5,
    typical_serving_g: 200,
    color_hints: ['red', 'orange'],
  },

  // ━━━ INDIAN CURRIES & DISHES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Paneer Butter Masala',
    aliases: ['paneer butter masala', 'paneer makhani', 'butter paneer'],
    category: 'curry',
    calories: 220,
    protein: 10.0,
    carbs: 8.0,
    fat: 17.0,
    fiber: 1.2,
    typical_serving_g: 200,
    color_hints: ['orange', 'red'],
  },
  {
    name: 'Palak Paneer',
    aliases: ['palak paneer', 'saag paneer', 'spinach paneer'],
    category: 'curry',
    calories: 170,
    protein: 9.0,
    carbs: 6.5,
    fat: 13.0,
    fiber: 2.5,
    typical_serving_g: 200,
    color_hints: ['green'],
  },
  {
    name: 'Butter Chicken',
    aliases: ['butter chicken', 'murgh makhani', 'chicken makhani'],
    category: 'curry',
    calories: 195,
    protein: 14.5,
    carbs: 7.0,
    fat: 13.0,
    fiber: 1.0,
    typical_serving_g: 250,
    color_hints: ['orange', 'red'],
  },
  {
    name: 'Chicken Tikka Masala',
    aliases: ['chicken tikka masala', 'tikka masala'],
    category: 'curry',
    calories: 170,
    protein: 15.0,
    carbs: 6.0,
    fat: 10.0,
    fiber: 1.0,
    typical_serving_g: 250,
    color_hints: ['orange', 'red'],
  },
  {
    name: 'Aloo Gobi',
    aliases: ['aloo gobi', 'alu gobi', 'potato cauliflower'],
    category: 'curry',
    calories: 120,
    protein: 3.0,
    carbs: 13.0,
    fat: 6.5,
    fiber: 2.5,
    typical_serving_g: 200,
    color_hints: ['yellow', 'white'],
  },
  {
    name: 'Malai Kofta',
    aliases: ['malai kofta'],
    category: 'curry',
    calories: 215,
    protein: 6.0,
    carbs: 14.0,
    fat: 15.5,
    fiber: 1.5,
    typical_serving_g: 200,
    color_hints: ['orange', 'cream'],
  },
  {
    name: 'Kadai Paneer',
    aliases: ['kadai paneer', 'karahi paneer', 'kadhai paneer'],
    category: 'curry',
    calories: 200,
    protein: 10.0,
    carbs: 7.0,
    fat: 15.0,
    fiber: 1.5,
    typical_serving_g: 200,
    color_hints: ['red', 'orange'],
  },
  {
    name: 'Shahi Paneer',
    aliases: ['shahi paneer'],
    category: 'curry',
    calories: 240,
    protein: 10.0,
    carbs: 9.0,
    fat: 18.0,
    fiber: 1.0,
    typical_serving_g: 200,
    color_hints: ['orange', 'cream'],
  },
  {
    name: 'Dal Makhani',
    aliases: ['dal makhani', 'maa ki dal', 'black dal'],
    category: 'curry',
    calories: 150,
    protein: 6.5,
    carbs: 14.0,
    fat: 8.0,
    fiber: 3.0,
    typical_serving_g: 200,
    color_hints: ['dark brown', 'black'],
  },
  {
    name: 'Baingan Bharta',
    aliases: ['baingan bharta', 'baingan ka bharta', 'eggplant mash'],
    category: 'curry',
    calories: 95,
    protein: 2.5,
    carbs: 8.0,
    fat: 6.0,
    fiber: 3.0,
    typical_serving_g: 200,
    color_hints: ['brown', 'green'],
  },
  {
    name: 'Matar Paneer',
    aliases: ['matar paneer', 'mattar paneer', 'peas paneer'],
    category: 'curry',
    calories: 180,
    protein: 9.0,
    carbs: 10.0,
    fat: 12.0,
    fiber: 2.0,
    typical_serving_g: 200,
    color_hints: ['red', 'green', 'orange'],
  },
  {
    name: 'Bhindi Masala',
    aliases: ['bhindi masala', 'bhindi fry', 'okra masala'],
    category: 'curry',
    calories: 110,
    protein: 3.0,
    carbs: 10.0,
    fat: 7.0,
    fiber: 3.0,
    typical_serving_g: 150,
    color_hints: ['green', 'brown'],
  },
  {
    name: 'Mix Veg Curry',
    aliases: ['mix veg', 'mixed vegetable', 'sabzi', 'mix veg curry', 'vegetable curry'],
    category: 'curry',
    calories: 100,
    protein: 3.0,
    carbs: 10.0,
    fat: 5.5,
    fiber: 3.0,
    typical_serving_g: 200,
    color_hints: ['orange', 'green', 'yellow'],
  },

  // ━━━ INDIAN SNACKS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Samosa',
    aliases: ['samosa', 'aloo samosa', 'veg samosa'],
    category: 'snack',
    calories: 262,
    protein: 4.5,
    carbs: 28.0,
    fat: 15.0,
    fiber: 2.0,
    typical_serving_g: 80,
    color_hints: ['golden', 'brown'],
  },
  {
    name: 'Pakora (Bhajia)',
    aliases: ['pakora', 'bhajia', 'pakode', 'onion pakora', 'aloo pakora', 'palak pakora', 'bhajiya'],
    category: 'snack',
    calories: 280,
    protein: 5.0,
    carbs: 22.0,
    fat: 19.0,
    fiber: 2.5,
    typical_serving_g: 100,
    color_hints: ['golden', 'brown'],
  },
  {
    name: 'Vada Pav',
    aliases: ['vada pav', 'vada pao', 'batata vada'],
    category: 'snack',
    calories: 290,
    protein: 5.0,
    carbs: 35.0,
    fat: 15.0,
    fiber: 2.0,
    typical_serving_g: 150,
    color_hints: ['golden', 'yellow'],
  },
  {
    name: 'Pav Bhaji',
    aliases: ['pav bhaji', 'pao bhaji'],
    category: 'indian',
    calories: 210,
    protein: 5.0,
    carbs: 30.0,
    fat: 8.0,
    fiber: 3.0,
    typical_serving_g: 300,
    color_hints: ['orange', 'red', 'brown'],
  },
  {
    name: 'Dhokla',
    aliases: ['dhokla', 'khaman dhokla'],
    category: 'snack',
    calories: 160,
    protein: 5.0,
    carbs: 27.0,
    fat: 3.5,
    fiber: 1.5,
    typical_serving_g: 100,
    color_hints: ['yellow'],
  },
  {
    name: 'Kachori',
    aliases: ['kachori', 'kachori', 'dal kachori'],
    category: 'snack',
    calories: 320,
    protein: 6.0,
    carbs: 32.0,
    fat: 19.0,
    fiber: 2.0,
    typical_serving_g: 60,
    color_hints: ['golden', 'brown'],
  },
  {
    name: 'Aloo Tikki',
    aliases: ['aloo tikki', 'potato patty', 'tikki'],
    category: 'snack',
    calories: 200,
    protein: 3.5,
    carbs: 28.0,
    fat: 8.0,
    fiber: 2.0,
    typical_serving_g: 80,
    color_hints: ['golden', 'brown'],
  },
  {
    name: 'Pani Puri (Golgappa)',
    aliases: ['pani puri', 'gol gappa', 'golgappa', 'puchka'],
    category: 'snack',
    calories: 35,
    protein: 0.5,
    carbs: 5.0,
    fat: 1.5,
    fiber: 0.3,
    typical_serving_g: 15,
    color_hints: ['golden', 'brown'],
  },
  {
    name: 'Sev Puri',
    aliases: ['sev puri', 'chaat'],
    category: 'snack',
    calories: 220,
    protein: 4.0,
    carbs: 25.0,
    fat: 12.0,
    fiber: 2.0,
    typical_serving_g: 150,
    color_hints: ['yellow', 'green', 'red'],
  },
  {
    name: 'Dahi Vada',
    aliases: ['dahi vada', 'dahi bhalla', 'curd vada'],
    category: 'snack',
    calories: 150,
    protein: 5.0,
    carbs: 18.0,
    fat: 7.0,
    fiber: 1.5,
    typical_serving_g: 150,
    color_hints: ['white', 'yellow'],
  },
  {
    name: 'Medu Vada',
    aliases: ['medu vada', 'vada', 'urad vada'],
    category: 'snack',
    calories: 290,
    protein: 12.0,
    carbs: 28.0,
    fat: 15.0,
    fiber: 3.0,
    typical_serving_g: 60,
    color_hints: ['golden', 'brown'],
  },

  // ━━━ MEAT & POULTRY ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Chicken Breast (cooked)',
    aliases: ['chicken breast', 'grilled chicken', 'boiled chicken', 'tandoori chicken breast'],
    category: 'poultry',
    calories: 165,
    protein: 31.0,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    typical_serving_g: 150,
    color_hints: ['white', 'brown'],
  },
  {
    name: 'Chicken Thigh (cooked)',
    aliases: ['chicken thigh', 'chicken leg', 'chicken drumstick'],
    category: 'poultry',
    calories: 209,
    protein: 26.0,
    carbs: 0,
    fat: 10.9,
    fiber: 0,
    typical_serving_g: 130,
    color_hints: ['brown', 'golden'],
  },
  {
    name: 'Tandoori Chicken',
    aliases: ['tandoori chicken', 'tanduri chicken'],
    category: 'poultry',
    calories: 195,
    protein: 28.0,
    carbs: 3.0,
    fat: 8.0,
    fiber: 0.5,
    typical_serving_g: 200,
    color_hints: ['red', 'orange'],
  },
  {
    name: 'Chicken Curry',
    aliases: ['chicken curry', 'murgh curry', 'chicken gravy'],
    category: 'curry',
    calories: 170,
    protein: 14.0,
    carbs: 6.0,
    fat: 10.5,
    fiber: 1.0,
    typical_serving_g: 250,
    color_hints: ['brown', 'orange'],
  },
  {
    name: 'Mutton Curry',
    aliases: ['mutton curry', 'gosht', 'lamb curry', 'mutton masala', 'rogan josh'],
    category: 'curry',
    calories: 200,
    protein: 15.0,
    carbs: 5.0,
    fat: 14.0,
    fiber: 1.0,
    typical_serving_g: 250,
    color_hints: ['brown', 'red'],
  },
  {
    name: 'Chicken Tikka',
    aliases: ['chicken tikka', 'tikka chicken'],
    category: 'poultry',
    calories: 175,
    protein: 24.0,
    carbs: 4.0,
    fat: 7.0,
    fiber: 0.5,
    typical_serving_g: 150,
    color_hints: ['red', 'orange'],
  },
  {
    name: 'Seekh Kebab',
    aliases: ['seekh kebab', 'kebab', 'sheek kebab', 'kabab'],
    category: 'meat',
    calories: 230,
    protein: 18.0,
    carbs: 5.0,
    fat: 16.0,
    fiber: 0.5,
    typical_serving_g: 100,
    color_hints: ['brown', 'golden'],
  },
  {
    name: 'Fish Curry',
    aliases: ['fish curry', 'machli curry', 'fish masala'],
    category: 'curry',
    calories: 140,
    protein: 15.0,
    carbs: 5.0,
    fat: 7.0,
    fiber: 1.0,
    typical_serving_g: 250,
    color_hints: ['yellow', 'orange', 'red'],
  },
  {
    name: 'Fried Fish',
    aliases: ['fried fish', 'fish fry', 'tawa fish', 'machli fry'],
    category: 'seafood',
    calories: 240,
    protein: 20.0,
    carbs: 10.0,
    fat: 14.0,
    fiber: 0.5,
    typical_serving_g: 120,
    color_hints: ['golden', 'brown'],
  },
  {
    name: 'Egg Curry',
    aliases: ['egg curry', 'anda curry', 'egg masala'],
    category: 'curry',
    calories: 150,
    protein: 10.0,
    carbs: 6.0,
    fat: 10.0,
    fiber: 1.0,
    typical_serving_g: 200,
    color_hints: ['yellow', 'orange', 'brown'],
  },
  {
    name: 'Prawn Curry',
    aliases: ['prawn curry', 'shrimp curry', 'jhinga curry'],
    category: 'curry',
    calories: 130,
    protein: 15.0,
    carbs: 5.0,
    fat: 6.0,
    fiber: 1.0,
    typical_serving_g: 200,
    color_hints: ['orange', 'red'],
  },

  // ━━━ EGGS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Boiled Egg',
    aliases: ['boiled egg', 'hard boiled egg', 'egg', 'anda'],
    category: 'egg',
    calories: 155,
    protein: 13.0,
    carbs: 1.1,
    fat: 11.0,
    fiber: 0,
    typical_serving_g: 50,
    color_hints: ['white', 'yellow'],
  },
  {
    name: 'Scrambled Eggs',
    aliases: ['scrambled eggs', 'egg bhurji', 'anda bhurji'],
    category: 'egg',
    calories: 148,
    protein: 10.0,
    carbs: 1.6,
    fat: 11.0,
    fiber: 0,
    typical_serving_g: 100,
    color_hints: ['yellow'],
  },
  {
    name: 'Omelette',
    aliases: ['omelette', 'omelet', 'egg omelette', 'masala omelette'],
    category: 'egg',
    calories: 154,
    protein: 11.0,
    carbs: 1.6,
    fat: 12.0,
    fiber: 0,
    typical_serving_g: 80,
    color_hints: ['yellow', 'golden'],
  },
  {
    name: 'Fried Egg',
    aliases: ['fried egg', 'sunny side up', 'egg fry'],
    category: 'egg',
    calories: 196,
    protein: 13.6,
    carbs: 0.8,
    fat: 15.3,
    fiber: 0,
    typical_serving_g: 60,
    color_hints: ['white', 'yellow'],
  },

  // ━━━ DAIRY ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Milk (whole)',
    aliases: ['milk', 'whole milk', 'full cream milk', 'doodh'],
    category: 'dairy',
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    typical_serving_g: 250,
    color_hints: ['white'],
  },
  {
    name: 'Paneer (Cottage Cheese)',
    aliases: ['paneer', 'cottage cheese', 'indian cheese'],
    category: 'dairy',
    calories: 265,
    protein: 18.3,
    carbs: 1.2,
    fat: 20.8,
    fiber: 0,
    typical_serving_g: 100,
    color_hints: ['white'],
  },
  {
    name: 'Curd (Yogurt)',
    aliases: ['curd', 'yogurt', 'dahi', 'plain yogurt'],
    category: 'dairy',
    calories: 60,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0,
    typical_serving_g: 150,
    color_hints: ['white'],
  },
  {
    name: 'Lassi',
    aliases: ['lassi', 'sweet lassi', 'mango lassi', 'salted lassi'],
    category: 'dairy',
    calories: 90,
    protein: 3.0,
    carbs: 13.0,
    fat: 3.0,
    fiber: 0,
    typical_serving_g: 250,
    color_hints: ['white', 'yellow'],
  },
  {
    name: 'Buttermilk (Chaas)',
    aliases: ['buttermilk', 'chaas', 'chaach', 'mattha'],
    category: 'dairy',
    calories: 40,
    protein: 3.3,
    carbs: 4.8,
    fat: 0.9,
    fiber: 0,
    typical_serving_g: 250,
    color_hints: ['white'],
  },
  {
    name: 'Raita',
    aliases: ['raita', 'boondi raita', 'cucumber raita', 'onion raita'],
    category: 'dairy',
    calories: 55,
    protein: 2.5,
    carbs: 4.5,
    fat: 3.0,
    fiber: 0.3,
    typical_serving_g: 100,
    color_hints: ['white', 'green'],
  },
  {
    name: 'Cheese',
    aliases: ['cheese', 'cheddar', 'mozzarella', 'processed cheese', 'cheese slice'],
    category: 'dairy',
    calories: 350,
    protein: 25.0,
    carbs: 1.3,
    fat: 27.0,
    fiber: 0,
    typical_serving_g: 30,
    color_hints: ['yellow', 'white'],
  },
  {
    name: 'Ghee',
    aliases: ['ghee', 'clarified butter', 'desi ghee'],
    category: 'oil',
    calories: 900,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    typical_serving_g: 10,
    color_hints: ['yellow', 'golden'],
  },
  {
    name: 'Butter',
    aliases: ['butter', 'makhan'],
    category: 'dairy',
    calories: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81.0,
    fiber: 0,
    typical_serving_g: 10,
    color_hints: ['yellow'],
  },

  // ━━━ DESSERTS & SWEETS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Gulab Jamun',
    aliases: ['gulab jamun'],
    category: 'sweet',
    calories: 380,
    protein: 5.0,
    carbs: 48.0,
    fat: 19.0,
    fiber: 0.5,
    typical_serving_g: 40,
    color_hints: ['brown', 'dark brown'],
  },
  {
    name: 'Rasgulla',
    aliases: ['rasgulla', 'rosogolla'],
    category: 'sweet',
    calories: 186,
    protein: 5.0,
    carbs: 36.0,
    fat: 2.5,
    fiber: 0,
    typical_serving_g: 50,
    color_hints: ['white'],
  },
  {
    name: 'Jalebi',
    aliases: ['jalebi', 'jilabi'],
    category: 'sweet',
    calories: 380,
    protein: 3.0,
    carbs: 54.0,
    fat: 17.0,
    fiber: 0.3,
    typical_serving_g: 50,
    color_hints: ['orange', 'golden'],
  },
  {
    name: 'Kheer (Rice Pudding)',
    aliases: ['kheer', 'rice pudding', 'payasam', 'chawal ki kheer'],
    category: 'sweet',
    calories: 145,
    protein: 4.0,
    carbs: 20.0,
    fat: 5.5,
    fiber: 0.3,
    typical_serving_g: 150,
    color_hints: ['white', 'cream'],
  },
  {
    name: 'Gajar Ka Halwa',
    aliases: ['gajar ka halwa', 'carrot halwa', 'gajar halwa'],
    category: 'sweet',
    calories: 210,
    protein: 4.0,
    carbs: 27.0,
    fat: 10.0,
    fiber: 1.5,
    typical_serving_g: 150,
    color_hints: ['orange'],
  },
  {
    name: 'Ladoo',
    aliases: ['ladoo', 'laddoo', 'besan ladoo', 'motichoor ladoo', 'boondi ladoo'],
    category: 'sweet',
    calories: 420,
    protein: 8.0,
    carbs: 48.0,
    fat: 22.0,
    fiber: 1.5,
    typical_serving_g: 40,
    color_hints: ['yellow', 'orange'],
  },
  {
    name: 'Barfi',
    aliases: ['barfi', 'burfi', 'kaju barfi', 'kaju katli', 'cashew barfi'],
    category: 'sweet',
    calories: 400,
    protein: 7.0,
    carbs: 52.0,
    fat: 19.0,
    fiber: 0.5,
    typical_serving_g: 30,
    color_hints: ['white', 'silver', 'yellow'],
  },
  {
    name: 'Halwa',
    aliases: ['halwa', 'sooji halwa', 'suji halwa', 'atta halwa', 'sheera'],
    category: 'sweet',
    calories: 250,
    protein: 3.0,
    carbs: 35.0,
    fat: 12.0,
    fiber: 0.5,
    typical_serving_g: 100,
    color_hints: ['yellow', 'golden'],
  },
  {
    name: 'Ice Cream',
    aliases: ['ice cream', 'gelato', 'vanilla ice cream', 'chocolate ice cream'],
    category: 'dessert',
    calories: 207,
    protein: 3.5,
    carbs: 24.0,
    fat: 11.0,
    fiber: 0.7,
    typical_serving_g: 100,
    color_hints: ['white', 'brown', 'pink'],
  },
  {
    name: 'Chocolate Cake',
    aliases: ['chocolate cake', 'cake', 'pastry', 'birthday cake'],
    category: 'dessert',
    calories: 371,
    protein: 5.0,
    carbs: 50.0,
    fat: 17.0,
    fiber: 2.0,
    typical_serving_g: 80,
    color_hints: ['brown', 'dark brown'],
  },
  {
    name: 'Brownie',
    aliases: ['brownie', 'chocolate brownie'],
    category: 'dessert',
    calories: 405,
    protein: 5.0,
    carbs: 50.5,
    fat: 21.0,
    fiber: 2.0,
    typical_serving_g: 60,
    color_hints: ['dark brown'],
  },
  {
    name: 'Cookie',
    aliases: ['cookie', 'cookies', 'biscuit', 'chocolate chip cookie'],
    category: 'sweet',
    calories: 488,
    protein: 5.0,
    carbs: 65.0,
    fat: 24.0,
    fiber: 2.0,
    typical_serving_g: 30,
    color_hints: ['golden', 'brown'],
  },

  // ━━━ NUTS & SEEDS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Almonds',
    aliases: ['almonds', 'badam'],
    category: 'nut',
    calories: 579,
    protein: 21.2,
    carbs: 21.7,
    fat: 49.9,
    fiber: 12.5,
    typical_serving_g: 30,
    color_hints: ['brown'],
  },
  {
    name: 'Cashews',
    aliases: ['cashews', 'kaju', 'cashew nuts'],
    category: 'nut',
    calories: 553,
    protein: 18.2,
    carbs: 30.2,
    fat: 43.9,
    fiber: 3.3,
    typical_serving_g: 30,
    color_hints: ['white', 'cream'],
  },
  {
    name: 'Peanuts',
    aliases: ['peanuts', 'moongfali', 'groundnuts', 'roasted peanuts'],
    category: 'nut',
    calories: 567,
    protein: 25.8,
    carbs: 16.1,
    fat: 49.2,
    fiber: 8.5,
    typical_serving_g: 30,
    color_hints: ['brown'],
  },
  {
    name: 'Walnuts',
    aliases: ['walnuts', 'akhrot'],
    category: 'nut',
    calories: 654,
    protein: 15.2,
    carbs: 13.7,
    fat: 65.2,
    fiber: 6.7,
    typical_serving_g: 30,
    color_hints: ['brown'],
  },
  {
    name: 'Pistachios',
    aliases: ['pistachios', 'pista'],
    category: 'nut',
    calories: 560,
    protein: 20.2,
    carbs: 27.2,
    fat: 45.3,
    fiber: 10.6,
    typical_serving_g: 30,
    color_hints: ['green', 'brown'],
  },

  // ━━━ FAST FOOD & INTERNATIONAL ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Pizza',
    aliases: ['pizza', 'cheese pizza', 'pepperoni pizza', 'margherita pizza', 'pizza slice'],
    category: 'pizza',
    calories: 266,
    protein: 11.0,
    carbs: 33.0,
    fat: 10.0,
    fiber: 2.3,
    typical_serving_g: 120,
    color_hints: ['red', 'yellow', 'brown'],
  },
  {
    name: 'Burger',
    aliases: ['burger', 'hamburger', 'cheeseburger', 'veg burger', 'chicken burger'],
    category: 'fast_food',
    calories: 295,
    protein: 17.0,
    carbs: 24.0,
    fat: 14.0,
    fiber: 1.3,
    typical_serving_g: 200,
    color_hints: ['brown', 'green', 'red'],
  },
  {
    name: 'French Fries',
    aliases: ['french fries', 'fries', 'chips', 'potato fries'],
    category: 'fast_food',
    calories: 312,
    protein: 3.4,
    carbs: 41.4,
    fat: 15.0,
    fiber: 3.8,
    typical_serving_g: 150,
    color_hints: ['golden', 'yellow'],
  },
  {
    name: 'Hot Dog',
    aliases: ['hot dog', 'hotdog', 'sausage'],
    category: 'fast_food',
    calories: 290,
    protein: 10.0,
    carbs: 24.0,
    fat: 17.0,
    fiber: 0.8,
    typical_serving_g: 100,
    color_hints: ['brown', 'red'],
  },
  {
    name: 'Sandwich',
    aliases: ['sandwich', 'veg sandwich', 'grilled sandwich', 'club sandwich', 'panini'],
    category: 'sandwich',
    calories: 250,
    protein: 10.0,
    carbs: 28.0,
    fat: 11.0,
    fiber: 2.0,
    typical_serving_g: 150,
    color_hints: ['brown', 'green', 'white'],
  },
  {
    name: 'Wrap / Roll',
    aliases: ['wrap', 'roll', 'chicken roll', 'kathi roll', 'frankie', 'shawarma', 'burrito'],
    category: 'fast_food',
    calories: 220,
    protein: 10.0,
    carbs: 25.0,
    fat: 9.0,
    fiber: 2.0,
    typical_serving_g: 200,
    color_hints: ['brown', 'golden'],
  },
  {
    name: 'Fried Chicken',
    aliases: ['fried chicken', 'chicken wings', 'chicken nuggets', 'chicken strips', 'popcorn chicken'],
    category: 'fast_food',
    calories: 307,
    protein: 22.0,
    carbs: 12.0,
    fat: 20.0,
    fiber: 0.5,
    typical_serving_g: 150,
    color_hints: ['golden', 'brown'],
  },
  {
    name: 'Taco',
    aliases: ['taco', 'tacos'],
    category: 'mexican',
    calories: 226,
    protein: 9.0,
    carbs: 20.0,
    fat: 12.0,
    fiber: 2.0,
    typical_serving_g: 100,
    color_hints: ['yellow', 'brown', 'green'],
  },
  {
    name: 'Sushi',
    aliases: ['sushi', 'sushi roll', 'maki', 'nigiri'],
    category: 'japanese',
    calories: 143,
    protein: 5.6,
    carbs: 25.0,
    fat: 2.0,
    fiber: 0.8,
    typical_serving_g: 150,
    color_hints: ['white', 'green', 'orange'],
  },
  {
    name: 'Fried Rice',
    aliases: ['fried rice', 'veg fried rice', 'chicken fried rice', 'egg fried rice', 'schezwan fried rice'],
    category: 'chinese',
    calories: 163,
    protein: 4.0,
    carbs: 23.0,
    fat: 6.0,
    fiber: 1.0,
    typical_serving_g: 250,
    color_hints: ['brown', 'yellow'],
  },
  {
    name: 'Manchurian',
    aliases: ['manchurian', 'gobi manchurian', 'veg manchurian', 'chicken manchurian'],
    category: 'chinese',
    calories: 200,
    protein: 5.0,
    carbs: 22.0,
    fat: 10.0,
    fiber: 2.0,
    typical_serving_g: 200,
    color_hints: ['brown', 'red'],
  },
  {
    name: 'Spring Roll',
    aliases: ['spring roll', 'spring rolls', 'veg spring roll'],
    category: 'chinese',
    calories: 250,
    protein: 5.0,
    carbs: 26.0,
    fat: 14.0,
    fiber: 1.5,
    typical_serving_g: 80,
    color_hints: ['golden', 'brown'],
  },
  {
    name: 'Momos',
    aliases: ['momos', 'dumplings', 'dim sum', 'steamed momos', 'fried momos', 'veg momos', 'chicken momos'],
    category: 'chinese',
    calories: 160,
    protein: 7.0,
    carbs: 22.0,
    fat: 5.0,
    fiber: 1.0,
    typical_serving_g: 150,
    color_hints: ['white', 'golden'],
  },

  // ━━━ SOUPS & SALADS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Tomato Soup',
    aliases: ['tomato soup'],
    category: 'soup',
    calories: 42,
    protein: 1.0,
    carbs: 7.0,
    fat: 1.3,
    fiber: 0.8,
    typical_serving_g: 250,
    color_hints: ['red', 'orange'],
  },
  {
    name: 'Chicken Soup',
    aliases: ['chicken soup', 'chicken noodle soup'],
    category: 'soup',
    calories: 60,
    protein: 5.0,
    carbs: 5.0,
    fat: 2.0,
    fiber: 0.5,
    typical_serving_g: 250,
    color_hints: ['yellow'],
  },
  {
    name: 'Green Salad',
    aliases: ['green salad', 'salad', 'garden salad', 'vegetable salad', 'mixed salad'],
    category: 'salad',
    calories: 20,
    protein: 1.5,
    carbs: 3.5,
    fat: 0.2,
    fiber: 2.0,
    typical_serving_g: 150,
    color_hints: ['green'],
  },
  {
    name: 'Caesar Salad',
    aliases: ['caesar salad', 'chicken caesar salad'],
    category: 'salad',
    calories: 127,
    protein: 5.0,
    carbs: 7.0,
    fat: 9.0,
    fiber: 1.5,
    typical_serving_g: 200,
    color_hints: ['green', 'yellow'],
  },

  // ━━━ BEVERAGES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Tea (with milk & sugar)',
    aliases: ['tea', 'chai', 'masala chai', 'milk tea', 'cutting chai'],
    category: 'beverage',
    calories: 50,
    protein: 1.5,
    carbs: 8.0,
    fat: 1.5,
    fiber: 0,
    typical_serving_g: 200,
    color_hints: ['brown'],
  },
  {
    name: 'Coffee (with milk & sugar)',
    aliases: ['coffee', 'cappuccino', 'latte', 'filter coffee', 'kaapi'],
    category: 'beverage',
    calories: 65,
    protein: 2.0,
    carbs: 9.0,
    fat: 2.5,
    fiber: 0,
    typical_serving_g: 200,
    color_hints: ['brown', 'dark brown'],
  },
  {
    name: 'Orange Juice',
    aliases: ['orange juice', 'oj', 'fresh juice'],
    category: 'beverage',
    calories: 45,
    protein: 0.7,
    carbs: 10.4,
    fat: 0.2,
    fiber: 0.2,
    typical_serving_g: 250,
    color_hints: ['orange'],
  },
  {
    name: 'Mango Shake',
    aliases: ['mango shake', 'mango smoothie', 'aam ras'],
    category: 'beverage',
    calories: 90,
    protein: 2.5,
    carbs: 17.0,
    fat: 1.5,
    fiber: 0.5,
    typical_serving_g: 250,
    color_hints: ['yellow', 'orange'],
  },
  {
    name: 'Coconut Water',
    aliases: ['coconut water', 'nariyal pani', 'tender coconut'],
    category: 'beverage',
    calories: 19,
    protein: 0.7,
    carbs: 3.7,
    fat: 0.2,
    fiber: 1.1,
    typical_serving_g: 250,
    color_hints: ['clear', 'white'],
  },
  {
    name: 'Sugarcane Juice',
    aliases: ['sugarcane juice', 'ganne ka ras'],
    category: 'beverage',
    calories: 40,
    protein: 0,
    carbs: 10.0,
    fat: 0,
    fiber: 0,
    typical_serving_g: 250,
    color_hints: ['green', 'yellow'],
  },
  {
    name: 'Nimbu Pani (Lemonade)',
    aliases: ['nimbu pani', 'lemonade', 'lime water', 'shikanji'],
    category: 'beverage',
    calories: 30,
    protein: 0,
    carbs: 8.0,
    fat: 0,
    fiber: 0,
    typical_serving_g: 250,
    color_hints: ['yellow', 'green'],
  },
  {
    name: 'Soft Drink (Cola)',
    aliases: ['cola', 'soft drink', 'soda', 'coke', 'pepsi', 'sprite', 'fanta', 'thumsup'],
    category: 'beverage',
    calories: 42,
    protein: 0,
    carbs: 10.6,
    fat: 0,
    fiber: 0,
    typical_serving_g: 330,
    color_hints: ['brown', 'clear'],
  },

  // ━━━ SAUCES & CONDIMENTS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Tomato Ketchup',
    aliases: ['ketchup', 'tomato ketchup', 'tomato sauce'],
    category: 'sauce',
    calories: 112,
    protein: 1.0,
    carbs: 26.0,
    fat: 0.1,
    fiber: 0.3,
    typical_serving_g: 15,
    color_hints: ['red'],
  },
  {
    name: 'Mayonnaise',
    aliases: ['mayonnaise', 'mayo'],
    category: 'sauce',
    calories: 680,
    protein: 1.0,
    carbs: 0.6,
    fat: 75.0,
    fiber: 0,
    typical_serving_g: 15,
    color_hints: ['white', 'cream'],
  },
  {
    name: 'Green Chutney',
    aliases: ['green chutney', 'mint chutney', 'pudina chutney', 'coriander chutney'],
    category: 'sauce',
    calories: 45,
    protein: 2.0,
    carbs: 5.0,
    fat: 2.0,
    fiber: 2.0,
    typical_serving_g: 20,
    color_hints: ['green'],
  },
  {
    name: 'Pickle (Achaar)',
    aliases: ['pickle', 'achaar', 'achar', 'mango pickle', 'mixed pickle', 'lime pickle'],
    category: 'sauce',
    calories: 150,
    protein: 1.5,
    carbs: 10.0,
    fat: 12.0,
    fiber: 2.0,
    typical_serving_g: 10,
    color_hints: ['red', 'yellow', 'brown'],
  },

  // ━━━ MISCELLANEOUS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    name: 'Papad',
    aliases: ['papad', 'papadum', 'poppadom', 'appalam'],
    category: 'snack',
    calories: 360,
    protein: 18.0,
    carbs: 46.0,
    fat: 11.0,
    fiber: 5.0,
    typical_serving_g: 15,
    color_hints: ['golden', 'yellow'],
  },
  {
    name: 'Uttapam',
    aliases: ['uttapam', 'uttappa', 'onion uttapam'],
    category: 'indian',
    calories: 150,
    protein: 4.0,
    carbs: 24.0,
    fat: 4.0,
    fiber: 1.0,
    typical_serving_g: 150,
    color_hints: ['golden', 'white'],
  },
  {
    name: 'Appam',
    aliases: ['appam', 'hoppers'],
    category: 'indian',
    calories: 120,
    protein: 2.5,
    carbs: 22.0,
    fat: 2.5,
    fiber: 0.5,
    typical_serving_g: 80,
    color_hints: ['white', 'golden'],
  },
  {
    name: 'Thali (Mixed Plate)',
    aliases: ['thali', 'indian thali', 'veg thali', 'non veg thali'],
    category: 'indian',
    calories: 180,
    protein: 7.0,
    carbs: 25.0,
    fat: 6.0,
    fiber: 3.0,
    typical_serving_g: 500,
    color_hints: ['mixed'],
  },
  {
    name: 'Chole Bhature',
    aliases: ['chole bhature', 'chhole bhature'],
    category: 'indian',
    calories: 310,
    protein: 8.0,
    carbs: 36.0,
    fat: 15.0,
    fiber: 3.0,
    typical_serving_g: 300,
    color_hints: ['golden', 'brown', 'yellow'],
  },
  {
    name: 'Peanut Butter',
    aliases: ['peanut butter', 'peanut butter spread'],
    category: 'nut',
    calories: 588,
    protein: 25.0,
    carbs: 20.0,
    fat: 50.0,
    fiber: 6.0,
    typical_serving_g: 32,
    color_hints: ['brown'],
  },
  {
    name: 'Honey',
    aliases: ['honey', 'shahad'],
    category: 'sweet',
    calories: 304,
    protein: 0.3,
    carbs: 82.4,
    fat: 0,
    fiber: 0.2,
    typical_serving_g: 20,
    color_hints: ['golden', 'amber'],
  },
  {
    name: 'Sugar',
    aliases: ['sugar', 'white sugar', 'cheeni'],
    category: 'sweet',
    calories: 387,
    protein: 0,
    carbs: 100,
    fat: 0,
    fiber: 0,
    typical_serving_g: 5,
    color_hints: ['white'],
  },
  {
    name: 'Jaggery',
    aliases: ['jaggery', 'gur', 'gud'],
    category: 'sweet',
    calories: 383,
    protein: 0.4,
    carbs: 98.0,
    fat: 0.1,
    fiber: 0,
    typical_serving_g: 10,
    color_hints: ['brown', 'dark brown'],
  },
  {
    name: 'Dark Chocolate',
    aliases: ['dark chocolate', 'chocolate', 'chocolate bar'],
    category: 'sweet',
    calories: 546,
    protein: 5.0,
    carbs: 60.0,
    fat: 31.0,
    fiber: 7.0,
    typical_serving_g: 30,
    color_hints: ['dark brown'],
  },
  {
    name: 'Protein Bar',
    aliases: ['protein bar', 'granola bar', 'energy bar'],
    category: 'snack',
    calories: 350,
    protein: 20.0,
    carbs: 35.0,
    fat: 14.0,
    fiber: 4.0,
    typical_serving_g: 60,
    color_hints: ['brown'],
  },
  {
    name: 'Khakhra',
    aliases: ['khakhra', 'khakra'],
    category: 'snack',
    calories: 380,
    protein: 10.0,
    carbs: 56.0,
    fat: 13.0,
    fiber: 3.0,
    typical_serving_g: 30,
    color_hints: ['golden', 'brown'],
  },
  {
    name: 'Thepla',
    aliases: ['thepla', 'methi thepla'],
    category: 'bread',
    calories: 220,
    protein: 5.5,
    carbs: 30.0,
    fat: 9.0,
    fiber: 2.0,
    typical_serving_g: 50,
    color_hints: ['golden', 'green'],
  },
  {
    name: 'Masala Dosa',
    aliases: ['masala dosa', 'mysore masala dosa'],
    category: 'indian',
    calories: 180,
    protein: 4.5,
    carbs: 26.0,
    fat: 6.5,
    fiber: 1.5,
    typical_serving_g: 200,
    color_hints: ['golden', 'brown', 'yellow'],
  },
  {
    name: 'Paneer Tikka',
    aliases: ['paneer tikka', 'tandoori paneer'],
    category: 'indian',
    calories: 250,
    protein: 15.0,
    carbs: 8.0,
    fat: 18.0,
    fiber: 1.0,
    typical_serving_g: 150,
    color_hints: ['red', 'orange', 'white'],
  },
];

// ─── SEARCH / MATCHING ───────────────────────────────────────────────

/**
 * Fuzzy search the food database by name/alias.
 * Returns top N matches sorted by relevance score.
 */
export function searchFoodDatabase(query: string, topN = 5): FoodEntry[] {
  const normalizedQuery = query.toLowerCase().trim();
  if (!normalizedQuery) return [];

  const scored = FOOD_DATABASE.map((entry) => {
    let score = 0;

    // Exact name match
    if (entry.name.toLowerCase() === normalizedQuery) {
      score += 100;
    }

    // Exact alias match
    if (entry.aliases.some((a) => a.toLowerCase() === normalizedQuery)) {
      score += 90;
    }

    // Name starts with query
    if (entry.name.toLowerCase().startsWith(normalizedQuery)) {
      score += 70;
    }

    // Alias starts with query
    if (entry.aliases.some((a) => a.toLowerCase().startsWith(normalizedQuery))) {
      score += 60;
    }

    // Name contains query
    if (entry.name.toLowerCase().includes(normalizedQuery)) {
      score += 40;
    }

    // Any alias contains query
    if (entry.aliases.some((a) => a.toLowerCase().includes(normalizedQuery))) {
      score += 30;
    }

    // Query words match — for multi-word queries like "chicken butter"
    const queryWords = normalizedQuery.split(/\s+/);
    const nameWords = entry.name.toLowerCase();
    const allAliases = entry.aliases.join(' ').toLowerCase();
    const matchedWords = queryWords.filter(
      (w) => nameWords.includes(w) || allAliases.includes(w)
    );
    score += matchedWords.length * 15;

    return { entry, score };
  });

  return scored
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, topN)
    .map((s) => s.entry);
}

/**
 * Get a food entry by exact name (case-insensitive).
 */
export function getFoodByName(name: string): FoodEntry | undefined {
  const normalized = name.toLowerCase().trim();
  return FOOD_DATABASE.find(
    (entry) =>
      entry.name.toLowerCase() === normalized ||
      entry.aliases.some((a) => a.toLowerCase() === normalized)
  );
}

/**
 * Get all foods in a category.
 */
export function getFoodsByCategory(category: FoodCategory): FoodEntry[] {
  return FOOD_DATABASE.filter((entry) => entry.category === category);
}

/**
 * Get all unique category names.
 */
export function getAllCategories(): FoodCategory[] {
  return [...new Set(FOOD_DATABASE.map((e) => e.category))];
}
